-- CreateTable
CREATE TABLE `OrderAllowDetInt` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `srnNo` INTEGER NULL,
    `erp_no` VARCHAR(191) NULL,
    `orderdate` DATETIME(3) NULL,
    `product_type` VARCHAR(191) NULL,
    `style_no` VARCHAR(191) NULL,
    `colour` VARCHAR(191) NULL,
    `sizes` VARCHAR(191) NULL,
    `po_no` VARCHAR(191) NULL,
    `po_date` DATETIME(3) NULL,
    `unit_of_measure` VARCHAR(191) NULL,
    `confirm_qty` DOUBLE NULL,
    `extrapolation` DOUBLE NULL,
    `order_qty` DOUBLE NULL,
    `customer_name` VARCHAR(191) NULL,
    `delivery_date` DATETIME(3) NULL,
    `season` VARCHAR(191) NULL,
    `product_desc` VARCHAR(191) NULL,
    `ordertime` VARCHAR(191) NULL,
    `item_no` DOUBLE NULL,
    `articlecode` VARCHAR(191) NULL,
    `INSEAM` VARCHAR(191) NULL,
    `description` VARCHAR(191) NULL,
    `country_desc` VARCHAR(191) NULL,
    `sam` DOUBLE NULL,
    `Recd_Date` DATETIME(3) NULL,
    `ISCOMPLETE` BOOLEAN NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FabricINT` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `srnno` DOUBLE NULL,
    `unit_code1` VARCHAR(191) NULL,
    `material_dc` VARCHAR(191) NULL,
    `item_no` DOUBLE NULL,
    `color` VARCHAR(191) NULL,
    `posting_date` DATETIME(3) NULL,
    `entry_date` DATETIME(3) NULL,
    `entry_time` DOUBLE NULL,
    `user_id` INTEGER NULL,
    `qty` DOUBLE NULL,
    `uom` VARCHAR(191) NULL,
    `roll_no` VARCHAR(191) NULL,
    `material` VARCHAR(191) NULL,
    `material_desc` VARCHAR(191) NULL,
    `movement_type` DOUBLE NULL,
    `unit_code` DOUBLE NULL,
    `location` VARCHAR(191) NULL,
    `Supplier_code` VARCHAR(191) NULL,
    `supplier_name` VARCHAR(191) NULL,
    `Recd_Date` DATETIME(3) NULL,
    `shade` VARCHAR(191) NULL,
    `gsm` DOUBLE NULL,
    `roll_length` DOUBLE NULL,
    `length_mtrs` DOUBLE NULL,
    `actual_width` DOUBLE NULL,
    `sh_length` DOUBLE NULL,
    `sh_width` DOUBLE NULL,
    `grouping` VARCHAR(191) NULL,
    `customer_name` VARCHAR(191) NULL,
    `style_no` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
